import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
// const cloudinary = require("cloudinary").v2;
import { uploadImage } from "../common/cloudinary";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [imageUrl, setImageUrl] = useState(null);
  const [tags, setTags] = useState([]);

  const Clarifai = require("clarifai");
  const app = new Clarifai.App({
    apiKey: "ba07b46c0da241848601af79347b11bc",
  });

  useEffect(() => {});

  const handleImageUpload = async (e) => {
    console.log("e value", e.target.files[0]);
    const image = e.target.files[0];
    const formData = new FormData();
    formData.append("image", image);
    formData.append("file", image);
    formData.append("upload_preset", "my-uploads");
    console.log("formDataformDataformDataformDataformData", formData);
    const data = await fetch(
      "https://api.cloudinary.com/v1_1/dfmyeez0x/image/upload",
      {
        method: "POST",
        body: formData,
      }
    ).then((r) => r.json());
    console.log("datadatadatadatadatadatadatadatadata", data);
    setImageUrl(data.secure_url);
    generateHashtags(data.secure_url);
  };
  const generateHashtags = (image) => {
    app.models
      .predict(Clarifai.GENERAL_MODEL, image)
      .then((response) => {
        const tags = response.rawData.outputs[0].data.concepts.map(
          (concept) => concept.name
        );
        setTags(tags);
        console.log(tags);
      })
      .catch((err) => {
        console.error(err);
      });
  };
  return (
    <>
      <Head>
        <title>Hashtag generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta charset="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {/* <title>Creative - Start Bootstrap Theme</title> */}
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css"
          rel="stylesheet"
        />
        <link href="css/styles.css" rel="stylesheet" />
      </Head>
      <main className={styles.mainn}>
        <header class="masthead">
          <div class="container px-4 px-lg-5 h-100">
            <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
              <div class="col-lg-8 align-self-end">
                <h1 className="header-text">
                  AI POWERED SMART HASHTAG GENERATOR FOR YOUR IMAGES
                </h1>
                <hr class="divider" />
              </div>
              <div class="col-lg-8 align-self-baseline">
                {/* <input type="file" onChange={handleImageUpload} /> */}

                {/* <a class="btn btn-primary btn-xl" href="#about">
                  Find Out More
                </a> */}

                {/* {imageUrl && (
                  <div> */}
                <label
                  for="upload-photo"
                  className="text-white font-weight-bold"
                >
                  Upload Photo...
                </label>
                <input
                  type="file"
                  name="photo"
                  id="upload-photo"
                  onChange={handleImageUpload}
                />
                {/* </div>
                )} */}

                {imageUrl && (
                  <div>
                    <img
                      src={imageUrl}
                      alt="Uploaded Image"
                      className="uploaded-image"
                      accept="image/png, image/gif, image/jpeg"
                    />
                    {/* <div className="text-white font-weight-bold">
                      generated Hashtags are....
                    </div> */}
                    <div class="list-group">
                      <a
                        href="#"
                        class="list-group-item list-group-item-action active"
                      >
                        generated Hashtags are....
                      </a>

                      {tags.length > 0 &&
                        tags.map((tag, index) => {
                          return (
                            <a
                              href="#"
                              key={index}
                              className="list-group-item list-group-item-action"
                            >
                             {tag}
                            </a>
                          );
                        })}

                      {/* <a
                        href="#"
                        class="list-group-item list-group-item-action"
                      >
                        Dapibus ac facilisis in
                      </a>
                      <a
                        href="#"
                        class="list-group-item list-group-item-action"
                      >
                        Morbi leo risus
                      </a>
                      <a
                        href="#"
                        class="list-group-item list-group-item-action"
                      >
                        Porta ac consectetur ac
                      </a>
                      <a
                        href="#"
                        class="list-group-item list-group-item-action disabled"
                      >
                        Vestibulum at eros
                      </a> */}
                      {}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </header>
      </main>
    </>
  );
}
